const segments={
  tienda_celulares_financia:{es:['celulares financiados','celulares a crédito','celulares en cuotas','teléfonos a crédito','smartphones financiados','tienda de celulares financiamiento'],en:['phones on finance','smartphones on finance','phone financing','mobile phone financing','smartphones on installments','phone store financing']},
  financiera_celulares:{es:['financiera de celulares','crédito para celulares','financiamiento de smartphones','crédito para teléfonos','financiamiento de dispositivos móviles'],en:['smartphone financing company','mobile phone finance company','phone financing company','device financing','mobile device financing']},
  electrodomesticos_financia_celulares:{es:['electrodomésticos celulares a crédito','tienda de electrónica financiamiento celulares','electrónica celulares financiados','tienda de electrónica cuotas celulares'],en:['electronics store phone financing','electronics retailer smartphone financing','appliance store smartphone financing','electronics store installments phones']},
  bnpl_smartphones:{es:['BNPL celulares','compra ahora paga después celulares','celulares buy now pay later'],en:['BNPL smartphones','buy now pay later phones','smartphone BNPL','phone installment financing']},
  telecom_financia_celulares:{es:['operador celular financia smartphones','telco celulares a cuotas','telecom celulares financiados'],en:['telecom smartphone financing','mobile operator phone installments','carrier smartphone financing']}
};
const regions={global:['global'],latin_america:['Mexico','Brazil','Colombia','Peru','Ecuador','Chile','Argentina','Dominican Republic','Guatemala','Costa Rica','Panama','Honduras','El Salvador','Bolivia','Paraguay','Uruguay'],north_america:['United States','Canada','Mexico'],europe:['United Kingdom','Spain','Germany','France','Italy','Portugal','Netherlands','Belgium','Ireland','Poland','Romania','Sweden','Norway'],africa:['Kenya','Nigeria','Ghana','Uganda','Tanzania','South Africa','Rwanda','Zambia','Ethiopia','Egypt'],asia:['India','Philippines','Indonesia','Malaysia','Thailand','Vietnam','Bangladesh','Pakistan','Japan','South Korea'],middle_east:['United Arab Emirates','Saudi Arabia','Jordan','Israel','Turkey','Qatar'],oceania:['Australia','New Zealand']};
const $=id=>document.getElementById(id);let generated=[];let seedLeads=[];
function build(){const segment=$('segment').value,language=$('language').value,region=$('country').value,extra=$('extra').value.trim();const chosen=segment==='all'?Object.keys(segments):[segment];const langs=language==='both'?['es','en']:[language];const places=regions[region]||['global'];generated=[];for(const s of chosen)for(const lang of langs)for(const place of places)for(const term of segments[s][lang])generated.push({segment:s,language:lang,place,query:`"${term}" ${place==='global'?'':`"${place}" `}${extra}`.trim()});generated=[...new Map(generated.map(x=>[x.query,x])).values()];$('queryCount').textContent=generated.length;$('queries').innerHTML=generated.slice(0,120).map((x,i)=>`<div class="query"><small>${i+1} · ${x.segment} · ${x.language.toUpperCase()} · ${x.place}</small><code>${escapeHtml(x.query)}</code></div>`).join('')||'<p>No hay consultas para los filtros seleccionados.</p>';}
function hasFinancingEvidence(x){return /financ|credit|cr[eé]dit|cuot|installment|BNPL|loan|finance/i.test(`${x.financing_evidence||''} ${x.financing_status||''}`)}
function hasPaymentTerms(x){return /cuot|installment|finance|financ|cr[eé]dit|BNPL|loan|credit|weekly|monthly|daily|deposit|down payment|0%/i.test(`${x.financing_evidence||''} ${x.financing_method||''}`)}
function hasNetwork(x){return Number(x.store_count)>1||/partner|network|dealer|store|retail|stores|merchant|sucursal|branch|agent/i.test(`${x.financing_evidence||''} ${x.commercial_angle||''} ${x.notes||''}`)}
function hasPublicContact(x){return Boolean(x.email||x.phone||x.contact_email||x.contact_phone||x.contact||x.public_contact)}
function hasRecentSource(x){if(x.source_date){const d=Date.parse(x.source_date);if(Number.isFinite(d))return (Date.now()-d)<=30*24*60*60*1000}return Boolean(x.source)}
function scoreLead(x){let score=0;if(hasFinancingEvidence(x))score+=40;if(hasPaymentTerms(x))score+=20;if(hasNetwork(x)||hasPublicContact(x))score+=15;if(hasRecentSource(x))score+=10;return Math.min(score,85)}
function renderSeeds(){const el=$('seedLeads');if(!el)return;const filter=$('leadFilter')?.value||'all';const ordered=seedLeads.map(x=>({...x,company:x.company||x.company_name,ancar_angle:x.ancar_angle||x.commercial_angle||'',score:Number.isFinite(Number(x.score))?Number(x.score):scoreLead(x),status:x.status||'new'})).filter(x=>filter==='all'||x.status===filter).sort((a,b)=>b.score-a.score);el.innerHTML=ordered.map((x,i)=>`<article class="lead-card"><div><strong>${i+1}. ${escapeHtml(x.company)}</strong><span>${escapeHtml(x.country)} · ${escapeHtml(x.business_type)}</span></div><p>${escapeHtml(x.financing_evidence||'')}</p><div class="lead-meta"><b>Score: ${x.score}/100</b><span>${escapeHtml(x.status)}</span></div><a href="${encodeURI(x.website||'#')}" target="_blank" rel="noopener">Fuente / website</a><small>${escapeHtml(x.ancar_angle)}</small></article>`).join('')||'<p>No hay leads para este filtro.</p>';}
function exportLeads(){const rows=[['company_name','country','business_type','language','financing_status','financing_evidence','website','source','source_date','financing_method','phone_brands','store_count','score','status','commercial_angle','notes'],...seedLeads.map(x=>[x.company_name||x.company,x.country,x.business_type,x.language,x.financing_status||'',x.financing_evidence||'',x.website||'',x.source||'',x.source_date||'',x.financing_method||'',Array.isArray(x.phone_brands)?x.phone_brands.join('; '):'',x.store_count??'',x.score??scoreLead(x),x.status||'new',x.commercial_angle||x.ancar_angle||'',x.notes||''])];const text=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download='ancar-verified-leads.csv';a.click();URL.revokeObjectURL(a.href)}
function escapeHtml(v){return String(v??'').replace(/[&<>\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]||c));}
function csv(){if(!generated.length)build();const rows=[['segment','language','place','query'],...generated.map(x=>[x.segment,x.language,x.place,x.query])];const text=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download='ancar-global-search-queries.csv';a.click();URL.revokeObjectURL(a.href)}
async function loadSeeds(){try{const r=await fetch('data/verified-leads-normalized.json',{cache:'no-store'});if(!r.ok)throw new Error('normalized lead load failed');seedLeads=await r.json();renderSeeds()}catch(e){$('seedLeads').innerHTML='<p>No se pudieron cargar los leads verificados.</p>'}}
$('build').addEventListener('click',build);$('export').addEventListener('click',csv);$('exportLeads').addEventListener('click',exportLeads);$('leadFilter')?.addEventListener('change',renderSeeds);build();loadSeeds();