const regions={global:[''],latin_america:['Mexico','Brazil','Colombia','Peru','Ecuador','Chile','Argentina','Dominican Republic','Guatemala','Costa Rica','Panama','Honduras','El Salvador','Bolivia','Paraguay','Uruguay'],north_america:['United States','Canada','Mexico'],europe:['United Kingdom','Spain','Germany','France','Italy','Portugal','Netherlands','Belgium','Ireland','Poland','Romania','Sweden','Norway'],africa:['Kenya','Nigeria','Ghana','Uganda','Tanzania','South Africa','Rwanda','Zambia','Ethiopia','Egypt'],asia:['India','Philippines','Indonesia','Malaysia','Thailand','Vietnam','Bangladesh','Pakistan','Japan','South Korea'],middle_east:['United Arab Emirates','Saudi Arabia','Jordan','Israel','Turkey','Qatar'],oceania:['Australia','New Zealand']};
const intents={es:['"contacto"','"teléfono" OR "whatsapp"','"precios" OR "cotización"','"servicios" OR "productos"','"sucursales" OR "ubicaciones"','"dueño" OR "gerente"','"comprar" OR "contratar"'],en:['"contact"','"phone" OR "whatsapp"','"pricing" OR "quote"','"services" OR "products"','"locations" OR "branches"','"owner" OR "manager"','"buy" OR "hire"']};
const $=id=>document.getElementById(id);let generated=[];let seedLeads=[];
function build(){const niche=($('niche')?.value||'').trim();const language=$('language').value;const region=$('country').value;const customer=$('segment').value;const extra=($('extra')?.value||'').trim();if(!niche){$('queries').innerHTML='<p>Escribe un nicho para generar consultas.</p>';$('queryCount').textContent='0';generated=[];return}const langs=language==='both'?['es','en']:[language];const places=regions[region]||[''];generated=[];for(const lang of langs)for(const place of places)for(const intent of intents[lang]){const customerTerm=customer==='b2b'?(lang==='en'?'business company':'empresa negocio'):customer==='b2c'?(lang==='en'?'consumer customer':'cliente consumidor'):(lang==='en'?'business customer':'empresa cliente');const q=[niche,customerTerm,place?`"${place}"`:'',intent,extra].filter(Boolean).join(' ');generated.push({language:lang,place,query:q})}generated=[...new Map(generated.map(x=>[x.query,x])).values()];$('queryCount').textContent=generated.length;$('queries').innerHTML=generated.slice(0,200).map((x,i)=>`<div class="query"><small>${i+1} · ${x.language.toUpperCase()} · ${escapeHtml(x.place||'Global')}</small><code>${escapeHtml(x.query)}</code><div class="query-actions"><a href="${searchUrl('google',x.query)}" target="_blank" rel="noopener noreferrer">Google</a><a href="${searchUrl('bing',x.query)}" target="_blank" rel="noopener noreferrer">Bing</a><button type="button" class="secondary copy-query" data-query="${escapeAttr(x.query)}">Copiar</button></div></div>`).join('');bindCopyButtons()}
function bindCopyButtons(){document.querySelectorAll('.copy-query').forEach(button=>button.addEventListener('click',async()=>{const query=button.dataset.query||'';try{await navigator.clipboard.writeText(query);const original=button.textContent;button.textContent='Copiado';setTimeout(()=>button.textContent=original,1200)}catch{button.textContent='No disponible';setTimeout(()=>button.textContent='Copiar',1200)}}))}
function searchUrl(engine,q){return `https://www.${engine==='bing'?'bing':'google'}.com/search?q=${encodeURIComponent(q)}`}
function isContactValue(v){const s=String(v||'').trim();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)||/\+?[0-9][0-9\s().-]{6,}/.test(s)||/^https?:\/\//i.test(s)}
function hasPublicContact(x){return [x.email,x.phone,x.contact_email,x.contact_phone,x.public_contact,x.contact].some(isContactValue)}
function scoreLead(x){let score=0;if(x.financing_evidence||x.need_evidence||x.problem_evidence||x.product_evidence)score+=40;if(x.financing_method||x.purchase_intent||x.service_interest||x.commercial_angle)score+=20;if(Number(x.store_count)>1||/network|dealer|branch|sucursal|location|multiple/i.test(`${x.commercial_angle||''} ${x.notes||''}`))score+=15;if(hasPublicContact(x))score+=15;if(x.source&&x.source_date){const d=Date.parse(x.source_date);if(Number.isFinite(d)&&d<=Date.now()&&Date.now()-d<=30*24*60*60*1000)score+=10}return Math.min(score,100)}
function normalizeLead(x){return {...x,company:x.company||x.company_name||'Sin nombre',score:scoreLead(x),status:String(x.status||'new').trim().toLowerCase()}}
function safeWebsite(v){const s=String(v||'').trim();if(!/^https?:\/\//i.test(s))return '';try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
function escapeHtml(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]||c))}
function escapeAttr(v){return escapeHtml(v).replace(/'/g,'&#39;')}
function getVisibleLeads(){const filter=$('leadFilter')?.value||'all';const country=($('leadCountry')?.value||'').trim().toLowerCase();const min=Number($('leadScore')?.value||0);const term=($('leadSearch')?.value||'').trim().toLowerCase();return seedLeads.map(normalizeLead).filter(x=>filter==='all'||x.status===filter).filter(x=>!country||String(x.country||'').toLowerCase().includes(country)).filter(x=>x.score>=min).filter(x=>!term||JSON.stringify(x).toLowerCase().includes(term)).sort((a,b)=>b.score-a.score||a.company.localeCompare(b.company))}
function renderSeeds(){const el=$('seedLeads');if(!el)return;const rows=getVisibleLeads();$('leadCount').textContent=rows.length;el.innerHTML=rows.map((x,i)=>`<article class="lead-card"><div><strong>${i+1}. ${escapeHtml(x.company)}</strong><span>${escapeHtml(x.country||'')} · ${escapeHtml(x.business_type||x.segment||'')}</span></div><p>${escapeHtml(x.financing_evidence||x.need_evidence||x.problem_evidence||x.product_evidence||'Sin evidencia detallada')}</p><div class="lead-meta"><b>Score: ${x.score}/100</b><span>${escapeHtml(x.status)}</span><span>Fuente: ${escapeHtml(x.source||'Sin fuente')}</span></div><div class="lead-links">${safeWebsite(x.website)?`<a href="${escapeHtml(safeWebsite(x.website))}" target="_blank" rel="noopener noreferrer">Website</a>`:'<span class="muted">Website no disponible</span>'} · ${renderContact(x)}</div></article>`).join('')||'<p>No hay leads para este filtro.</p>'}
function renderContact(x){for(const v of [x.email,x.contact_email,x.phone,x.contact_phone,x.public_contact,x.contact])if(isContactValue(v)){const s=String(v).trim();if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s))return `<a href="mailto:${escapeAttr(s)}">${escapeHtml(s)}</a>`;if(/^https?:\/\//i.test(s))return `<a href="${escapeAttr(s)}" target="_blank" rel="noopener noreferrer">Contacto</a>`;return `<a href="tel:${escapeAttr(s.replace(/[^+\d]/g,''))}">${escapeHtml(s)}</a>`}return '<span class="muted">Contacto no disponible</span>'}
function renderLeadStatusOptions(){const s=$('leadFilter');if(!s)return;const current=s.value||'all';const statuses=[...new Set(seedLeads.map(x=>String(x.status||'new').trim().toLowerCase()).filter(Boolean))];s.innerHTML='<option value="all">Todos</option>'+statuses.map(v=>`<option value="${escapeAttr(v)}">${escapeHtml(v.charAt(0).toUpperCase()+v.slice(1))}</option>`).join('');s.value=statuses.includes(current)?current:'all'}
function clearLeadFilters(){['leadCountry','leadSearch'].forEach(id=>$(id)&&($(id).value=''));if($('leadFilter'))$('leadFilter').value='all';if($('leadScore'))$('leadScore').value='0';renderSeeds()}
function downloadCsv(filename,rows){const text='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');const a=document.createElement('a');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csv(){if(!generated.length)build();downloadCsv('ancar-global-search-queries.csv',[['language','place','query'],...generated.map(x=>[x.language,x.place||'Global',x.query])])}
function exportLeads(){downloadCsv('ancar-leads.csv',[['company','country','business_type','status','score','website','source','source_date','contact'],...getVisibleLeads().map(x=>[x.company,x.country||'',x.business_type||x.segment||'',x.status,x.score,safeWebsite(x.website),x.source||'',x.source_date||'',x.email||x.phone||x.contact||''])])}
async function loadSeeds(){try{const r=await fetch('data/verified-leads-normalized.json',{cache:'no-store'});if(!r.ok)throw new Error('dataset load failed');const data=await r.json();if(!Array.isArray(data))throw new Error('dataset is not an array');seedLeads=data;renderLeadStatusOptions();renderSeeds()}catch(e){console.error(e);$('seedLeads').innerHTML='<p>No se pudieron cargar los leads verificados.</p>';$('leadCount').textContent='0'}}
$('build').addEventListener('click',build);$('export').addEventListener('click',csv);$('exportLeads').addEventListener('click',exportLeads);$('clearLeadFilters')?.addEventListener('click',clearLeadFilters);$('leadFilter')?.addEventListener('change',renderSeeds);$('leadCountry')?.addEventListener('input',renderSeeds);$('leadScore')?.addEventListener('change',renderSeeds);$('leadSearch')?.addEventListener('input',renderSeeds);build();loadSeeds();
