const segments={
  tienda_celulares_financia:{es:['celulares financiados','celulares a crédito','celulares en cuotas','teléfonos a crédito','smartphones financiados','tienda de celulares financiamiento'],en:['phones on finance','smartphones on finance','phone financing','mobile phone financing','smartphones on installments','phone store financing']},
  financiera_celulares:{es:['financiera de celulares','crédito para celulares','financiamiento de smartphones','crédito para teléfonos','financiamiento de dispositivos móviles'],en:['smartphone financing company','mobile phone finance company','phone financing company','device financing','mobile device financing']},
  electrodomesticos_financia_celulares:{es:['electrodomésticos celulares a crédito','tienda de electrónica financiamiento celulares','electrónica celulares financiados','tienda de electrónica cuotas celulares'],en:['electronics store phone financing','electronics retailer smartphone financing','appliance store smartphone financing','electronics store installments phones']},
  bnpl_smartphones:{es:['BNPL celulares','compra ahora paga después celulares','celulares buy now pay later'],en:['BNPL smartphones','buy now pay later phones','smartphone BNPL','phone installment financing']},
  telecom_financia_celulares:{es:['operador celular financia smartphones','telco celulares a cuotas','telecom celulares financiados'],en:['telecom smartphone financing','mobile operator phone installments','carrier smartphone financing']}
};
const regions={global:['global'],latin_america:['Mexico','Brazil','Colombia','Peru','Ecuador','Chile','Argentina','Dominican Republic','Guatemala','Costa Rica','Panama','Honduras','El Salvador','Bolivia','Paraguay','Uruguay'],north_america:['United States','Canada','Mexico'],europe:['United Kingdom','Spain','Germany','France','Italy','Portugal','Netherlands','Belgium','Ireland','Poland','Romania','Sweden','Norway'],africa:['Kenya','Nigeria','Ghana','Uganda','Tanzania','South Africa','Rwanda','Zambia','Ethiopia','Egypt'],asia:['India','Philippines','Indonesia','Malaysia','Thailand','Vietnam','Bangladesh','Pakistan','Japan','South Korea'],middle_east:['United Arab Emirates','Saudi Arabia','Jordan','Israel','Turkey','Qatar'],oceania:['Australia','New Zealand']};
const $=id=>document.getElementById(id);let generated=[];let seedLeads=[];
function build(){const segment=$('segment').value,language=$('language').value,region=$('country').value,extra=$('extra').value.trim();const chosen=segment==='all'?Object.keys(segments):[segment];const langs=language==='both'?['es','en']:[language];const places=regions[region]||['global'];generated=[];for(const s of chosen)for(const lang of langs)for(const place of places)for(const term of segments[s][lang])generated.push({segment:s,language:lang,place,query:`"${term}" ${place==='global'?'':`"${place}" `}${extra}`.trim()});generated=[...new Map(generated.map(x=>[x.query,x])).values()];$('queryCount').textContent=generated.length;$('queries').innerHTML=generated.slice(0,120).map((x,i)=>`<div class="query"><small>${i+1} · ${x.segment} · ${x.language.toUpperCase()} · ${x.place}</small><code>${escapeHtml(x.query)}</code></div>`).join('')||'<p>No hay consultas para los filtros seleccionados.</p>';}
function scoreLead(x){let score=40;if(/cuot|installment|finance|financ|cr[eé]dit|BNPL|loan|credit/i.test(x.financing_evidence))score+=20;if(/partner|network|dealer|store|retail|stores|merchant/i.test(`${x.financing_evidence} ${x.ancar_angle}`))score+=15;if(x.website)score+=15;if(x.source)score+=10;return Math.min(score,100)}
function renderSeeds(){const el=$('seedLeads');if(!el)return;const filter=$('leadFilter')?.value||'all';const ordered=seedLeads.map(x=>({...x,score:Number.isFinite(Number(x.score))?Number(x.score):scoreLead(x)})).filter(x=>filter==='all'||x.status===filter).sort((a,b)=>b.score-a.score);el.innerHTML=ordered.map((x,i)=>`<article class="lead-card"><div><strong>${i+1}. ${escapeHtml(x.company)}</strong><span>${escapeHtml(x.country)} · ${escapeHtml(x.business_type)}</span></div><p>${escapeHtml(x.financing_evidence)}</p><div class="lead-meta"><b>Score: ${x.score}/100</b><span>${escapeHtml(x.status||'pending_verification')}</span></div><a href="${encodeURI(x.website)}" target="_blank" rel="noopener">Fuente / website</a><small>${escapeHtml(x.ancar_angle)}</small></article>`).join('')||'<p>No hay leads para este filtro.</p>';}
function exportLeads(){const rows=[['company','country','business_type','language','financing_evidence','website','source','source_date','score','status','ancar_angle'],...seedLeads.map(x=>[x.company,x.country,x.business_type,x.language,x.financing_evidence,x.website,x.source,x.source_date||'',x.score??scoreLead(x),x.status||'pending_verification',x.ancar_angle])];const text=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download='ancar-verified-seed-leads.csv';a.click();URL.revokeObjectURL(a.href)}
function escapeHtml(v){return String(v).replace(/[&<>\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));}
function csv(){if(!generated.length)build();const rows=[['segment','language','place','query'],...generated.map(x=>[x.segment,x.language,x.place,x.query])];const text=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download='ancar-global-search-queries.csv';a.click();URL.revokeObjectURL(a.href)}
async function loadSeeds(){try{const r=await fetch('data/verified-seed-leads.json',{cache:'no-store'});if(!r.ok)throw new Error('seed load failed');seedLeads=await r.json();renderSeeds()}catch(e){$('seedLeads').innerHTML='<p>No se pudieron cargar las semillas verificadas.</p>'}}
$('build').addEventListener('click',build);$('export').addEventListener('click',csv);$('exportLeads').addEventListener('click',exportLeads);$('leadFilter')?.addEventListener('change',renderSeeds);build();loadSeeds();
